name: portfolio
description: A simple portfolio for Flutter Developer
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  asuka: ^2.2.0
  cupertino_icons: ^1.0.5
  auto_route: ^7.7.1
  bloc: ^8.1.2
  flutter_svg: ^2.0.7
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  riverbloc: ^2.2.0
  injectable: ^2.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  rxdart: ^0.27.7
  dartz: ^0.10.1
  dartx: ^1.2.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  rx_shared_preferences: ^3.0.0
  enum_annotation: ^0.0.4
  uuid: ^3.0.7
  lottie: ^2.5.0
  url_launcher: ^6.1.12
  responsive_framework: ^1.1.0
  responsive_sizer: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  riverpod_generator: ^2.2.4
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_lint: ^1.4.0
  freezed: ^2.4.1
  enum_generator: ^1.1.0
  json_serializable: ^6.7.1
  auto_route_generator: ^7.2.0
  injectable_generator: ^2.1.6
  flutter_gen_runner: ^5.3.1
  intl_utils: ^2.8.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
    - family: VisueltPro
      fonts:
        - asset: assets/fonts/visuelt/VisueltPro-Black.ttf
        - asset: assets/fonts/visuelt/VisueltPro-Bold.ttf
        - asset: assets/fonts/visuelt/VisueltPro-Italic.ttf
        - asset: assets/fonts/visuelt/VisueltPro-Light.ttf
        - asset: assets/fonts/visuelt/VisueltPro-Medium.ttf
        - asset: assets/fonts/visuelt/VisueltPro-Regular.ttf
        - asset: assets/fonts/visuelt/VisueltPro-Thin.ttf

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    lottie: true
    flare_flutter: false
    rive: false

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
  main_locale: 'en'
  arb_dir: assets/l10n
