name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Only works with v2
      - uses: subosito/flutter-action@v1
      - name: Preparing the source code
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          dart run intl_utils:generate
          
      - uses: bluefireteam/flutter-gh-pages@v7
      - uses: peaceiris/actions-gh-pages@v3
        with:
          cname: github.com
