name: Deploy to GitHub Pages

on:
  push:
    # Update branch according from where you will be pushing the code
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter pub run intl_utils:generate
      - uses: bluefireteam/flutter-gh-pages@v7